version: "3.7"

volumes:
  mysql-data:
    name: ${DB_DATA}
  mysql-socket:
  php-socket:

services:

  ##############################################################################
  # nginx
  ##############################################################################
  nginx:
    container_name: ${NGINX_CONTAINER}
    build:
      context: ./docker/nginx
    depends_on:
      - php
      - mysql
    ports:
      - ${WEB_PORT}:80
    volumes:
      - ${SRC_PATH}:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/logs/nginx:/var/log/nginx
      - php-socket:/var/run/php-fpm

  ##############################################################################
  # php
  ##############################################################################
  php:
    container_name: ${PHP_CONTAINER}
    build:
      context: ./docker/php
    ports:
      - ${PHP_PORT}:9000
    depends_on:
      - mysql
    volumes:
      - ${SRC_PATH}:/var/www/html
      - ./docker/php/php.ini:/etc/php/php.ini
      - ./docker/logs/nginx:/var/log/php
      - php-socket:/var/run/php-fpm
      - mysql-socket:/var/run/mysqld

  ##############################################################################
  # mysql
  ##############################################################################
  mysql:
    container_name: ${DB_CONTAINER}
    build:
      context: ./docker/mysql
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: 'Asia/Tokyo'
    command:
      mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/logs/mysql:/var/log/mysql
      - mysql-data:/var/lib/mysql
      - mysql-socket:/var/run/mysqld

  ##############################################################################
  # phpmyadmin
  ##############################################################################
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    depends_on:
      - mysql
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${DB_PASSWORD}
    ports:
      - ${PHPMYADMIN_PORT}:80
