version: '3.7'

volumes:
  mysql-data:
    name: ${DB_DATA}
  mysql-socket:

services:

  ##############################################################################
  # rust
  ##############################################################################
  rust:
    container_name: ${RUST_CONTAINER}
    build:
      context: ./docker/rust
      network: host
    depends_on:
      - mysql
    ports:
      - ${WEB_PORT}:80
    volumes:
      - ${SRC_PATH}:/var/www/html/
    tty: true

  ##############################################################################
  # mysql
  ##############################################################################
  mysql:
    container_name: ${DB_CONTAINER}
    build:
      context: ./docker/mysql
      network: host
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: 'Asia/Tokyo'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/logs/mysql:/var/log/mysql
      - mysql-data:/var/lib/mysql
      - mysql-socket:/var/run/mysqld
